# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b2005f7ca60dc18090a0842794eaa442446c8bc7806c09bb16b876e75151abb6b5a9f4d109b6ca05fb7343e1825ff331339f1765d43bd36e035d181881f9e35

test:
  secret_key_base: d07a7f9627ccaa0af22d8b5069c3b7412e92d750ee73d8e2eaaf4e015c10d5c655c5176f6d112b09c8eba8b4344e0f1bb371858577b6ffd76ddd71a6213acfe0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
